-- ============================================================
-- GatherPass — Supabase (PostgreSQL) Schema & Seed Data
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard)
-- ============================================================

-- 1. Create Events Table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    event_date TIMESTAMPTZ NOT NULL,
    venue VARCHAR(255) NOT NULL,
    base_ticket_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    capacity INT NOT NULL DEFAULT 100,
    available_tickets INT NOT NULL DEFAULT 100,
    picture TEXT,
    planner_name VARCHAR(255) DEFAULT 'GatherPass Official',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create Tickets Table
CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    buyer_name VARCHAR(255),
    buyer_email VARCHAR(255) NOT NULL,
    buyer_phone VARCHAR(50),
    quantity INT NOT NULL DEFAULT 1,
    ticket_type VARCHAR(100) NOT NULL DEFAULT 'General Admission',
    ticket_price NUMERIC(10, 2) NOT NULL,
    platform_fee NUMERIC(10, 2) NOT NULL,
    total_paid NUMERIC(10, 2) NOT NULL,
    ticket_token VARCHAR(64) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'valid',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Row-Level Security (RLS) Policies (Enable public read / service-role write)
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on active events"
    ON events FOR SELECT
    USING (is_active = TRUE);

CREATE POLICY "Allow service role full access on events"
    ON events FOR ALL
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow public read access on tickets by token"
    ON tickets FOR SELECT
    USING (true);

CREATE POLICY "Allow public insert on tickets"
    ON tickets FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow public update on tickets for verification"
    ON tickets FOR UPDATE
    USING (true)
    WITH CHECK (true);

-- 4. Seed Demo Events
INSERT INTO events (name, description, event_date, venue, base_ticket_price, capacity, available_tickets, picture, planner_name, is_active)
VALUES
(
    'Accra Tech Summit 2026',
    'The premier West African technology conference bringing together founders, investors, and engineers for keynote talks, product demos, and unmatched networking.',
    '2026-11-15 09:00:00+00',
    'Grand Arena, Accra International Conference Centre',
    150.00,
    500,
    500,
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80',
    'Tech Summit Africa',
    TRUE
),
(
    'Afrobeats & Vibes Festival',
    'An outdoor celebration of African music, culinary arts, fashion, and culture. Live headline sets from top artists and world-class sound design.',
    '2026-12-05 16:00:00+00',
    'Laboma Beachfront, Accra',
    80.00,
    1500,
    1500,
    'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&q=80',
    'Live Nation West Africa',
    TRUE
),
(
    'Founder Breakfast & Networking',
    'An exclusive morning roundtable for startup founders, angel investors, and venture builders. High-impact conversations over artisan coffee.',
    '2026-10-20 07:30:00+00',
    'Impact Hub Osu, Accra',
    45.00,
    60,
    60,
    'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=1200&q=80',
    'GatherPass Community',
    TRUE
)
ON CONFLICT DO NOTHING;
